# Generated by Django 3.2.16 on 2024-12-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congratulation',
            options={'ordering': ('-created_at',)},
        ),
    ]
