# Generated by Django 3.2.16 on 2024-12-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_birthday_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthday',
            options={'ordering': ('id',)},
        ),
    ]
